version: '3'
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  web:
    image: ssgraph
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./:/opt/
    command: python app.py
    depends_on:
      - redis
  worker:
    image: ssgraph
    restart: unless-stopped
    volumes:
      - ./:/opt/
    command: flask rq worker --worker-ttl=420
    depends_on:
      - redis
